# Generated by Django 4.0 on 2021-12-13 09:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(default=None, max_length=30)),
                ('age', models.IntegerField(blank=True, default=0)),
                ('lead', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'ordering': ['actor_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default=None, max_length=50)),
                ('rating', models.IntegerField(default=0)),
                ('cast', models.IntegerField(blank=True, default=1)),
                ('genre', models.CharField(blank=True, default='raw', max_length=20)),
                ('release_data', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 13, 9, 35, 57, 411585))),
            ],
            options={
                'ordering': ['movie_name'],
            },
        ),
        migrations.CreateModel(
            name='muv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(blank=True, default=None, max_length=20)),
                ('act', models.ManyToManyField(to='app.Actor')),
                ('muv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='idbm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(blank=True, default=None, max_length=20)),
                ('act', models.ManyToManyField(to='app.Actor')),
                ('muv', models.ManyToManyField(to='app.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movie',
            field=models.ManyToManyField(to='app.Movie'),
        ),
    ]
