# Generated by Django 4.0 on 2021-12-15 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 15, 10, 32, 19, 474922)),
        ),
    ]
