# Generated by Django 4.0 on 2021-12-17 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_alter_movie_release_data_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 6, 5, 25, 973299)),
        ),
    ]
