# Generated by Django 4.0 on 2021-12-17 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_alter_movie_release_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 6, 12, 6, 565115)),
        ),
    ]
